# Generated by Django 5.2.17 on 2026-09-23 16:33

import comments.attachments
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username may contain only latin letters and digits.",
                                regex="^[A-Za-z0-9]+$",
                            )
                        ],
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "home_page",
                    models.URLField(
                        blank=True,
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
                ("text", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True, upload_to=comments.attachments.attachment_upload_to
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        blank=True,
                        choices=[("image", "Image"), ("text", "Text file")],
                        max_length=5,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Direct parent comment. Empty for a top-level comment.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
                (
                    "root",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        help_text="Top-level comment of the thread. Empty for a top-level comment itself.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thread_comments",
                        to="comments.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="comments_co_created_5f6a12_idx"),
                    models.Index(fields=["user_name"], name="comments_co_user_na_e341a9_idx"),
                    models.Index(fields=["email"], name="comments_co_email_7ec44a_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("attachment", ""), ("attachment_type", "")),
                            models.Q(
                                models.Q(("attachment", ""), _negated=True),
                                models.Q(("attachment_type", ""), _negated=True),
                            ),
                            _connector="OR",
                        ),
                        name="attachment_and_type_are_set_together",
                    )
                ],
            },
        ),
    ]
